# Example configuration for running multiple appointment searches sequentially.
# Copy this file to appointments.toml and adjust the values to match your filters.

[settings]
loop_interval_seconds = 30

[[jobs]]
label = "job1"
region = 202
specialty = [27962]
doctor = 334258
notification = "telegram"
title = "Endokrynolog dorośli - porada telefoniczna"

[[jobs]]
label = "job2"
region = 202
specialty = [176]
doctor = 499430
notification = "telegram"
title = "Alergolog dorośli"

[[jobs]]
label = "job3"
region = 202
specialty = [178]
doctor = 499430
notification = "telegram"
title = "Alergolog dorośli odczulanie"

[[jobs]]
label = "job4"
region = 202
specialty = [192]
notification = "telegram"
title = "Laryngolog dorośli"
