# Example configuration for running multiple appointment searches sequentially.
# Copy this file to appointments.toml and adjust the values to match your filters.

[settings]
loop_interval_seconds = 60

[[jobs]]
label = "dermatologist"
region = 202
specialty = [3, 69362]
doctor = 103934
notification = "telegram"
title = "Dermatolog dorośli"
