app = "medichaser"
primary_region = "waw"

[build]
  dockerfile = "Dockerfile"

[env]
  APPOINTMENTS_CONFIG = "/app/data/appointments.toml"
  PYTHONUNBUFFERED = "1"

[processes]
  web = "ttyd -W bash"
  watcher = [
    "/bin/sh",
    "-c",
    "python medichaser.py find-appointments --config ${APPOINTMENTS_CONFIG}"
  ]

[[services]]
  processes = ["web"]
  internal_port = 7681
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[mounts]]
  source = "medichaser_data"
  destination = "/app/data"
