# fly.toml app configuration file generated for medichaser on 2025-09-21T12:06:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medichaser'
primary_region = 'waw'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  watcher = 'python medichaser.py find-appointments --config appointments.toml'

[[vm]]
  size = 'shared-cpu-1x'
